### ISSUE TITLE
wget on some links in download_igbh_large.sh returns ERROR 403

### ISSUE THREAD

**Issue by ska278** [IllinoisGraphBenchmark/IGB-Datasets#17]
The following wget requests in download_igbh_large.sh fail with ERROR 403: Forbidden. Not sure if the files are missing or have permission issues. Please fix. (All other links in the script work fine.)

wget https://igb-public.s3.us-east-2.amazonaws.com/large/processed/paper/node_label_19.npy
wget https://igb-public.s3.us-east-2.amazonaws.com/large/processed/paper/node_label_2K.npy

# paper__cites__paper
wget --recursive --no-parent https://igb-public.s3.us-east-2.amazonaws.com/large/processed/paper__cites__paper/edge_index.npy

# paper__cites__paper
wget https://igb-public.s3.us-east-2.amazonaws.com/large/processed/paper__cites__paper/edge_index.npy

# paper__published__journal
wget https://igb-public.s3.us-east-2.amazonaws.com/large/processed/paper__published__journal/edge_index.npy

# paper__topic__fos
wget https://igb-public.s3.us-east-2.amazonaws.com/large/processed/paper__topic__fos/edge_index.npy

# paper__venue__conference
wget https://igb-public.s3.us-east-2.amazonaws.com/large/processed/paper__venue__conference/edge_index.npy

# paper__written_by__author
wget https://igb-public.s3.us-east-2.amazonaws.com/large/processed/paper__written_by__author/edge_index.npy

**Comment by ska278** [comment]
Got all the data with changes to the paths. Thanks!

**Comment by msharmavikram** [comment]
This issue is not closed as the download script is not updated yet.

**Comment by akhatua2** [comment]
Bash script updated. Download script ongoing in #10.
