### ISSUE TITLE
Cannot get complete igbh-large dataset

### ISSUE THREAD

**Issue by kaixuanliu** [IllinoisGraphBenchmark/IGB-Datasets#18]
**Describe the bug**
We can get complete dataset for igbh-{‘tiny’,’small’,’medium’} now. However, we miss some part of IGBH-large dataset. For example, we cannot get ’ paper__cites__paper/edge_index.npy’ file as it returns 403 error for the link access

**To Reproduce**
./download_igbh_large.sh 

**Screenshots**
<img width="595" alt="image" src="https://github.com/IllinoisGraphBenchmark/IGB-Datasets/assets/13268042/1fc93ea5-d406-4fdc-bccc-816f441a4f65">

**Comment by msharmavikram** [comment]
Thanks for pointing this out. There is an error on the script that requires to be fixed. You can try downloading `download_igbh600m.sh` (the full version of the dataset for heterogeneous graphs). 

@akhatua2 This is the same bug we had on the homogenous side. Can you fix this with updated links?

**Comment by akhatua2** [comment]
Modified file path. Will update to zipped script soon.
