### ISSUE TITLE
Edge types used in heterogeneous training

### ISSUE THREAD

**Issue by LiSu** [IllinoisGraphBenchmark/IGB-Datasets#21]
Hi,

When training heterogeneous graphs using [train_hetero.py ](https://github.com/IllinoisGraphBenchmark/IGB-Datasets/blob/main/igb/train_hetero.py), is 'paper-cites-paper' the only type of edge used in sampling? As the default edge direction of DGL neighbor sampler is 'in', and the only 'in' edge for paper nodes is 'paper-cites-paper'.

Regards,
Li Su

**Comment by akhatua2** [comment]
Hi Li Su,

Thanks for bringing this feature of the DGL neighbor sampler to your notice. We will update the [dataloader.py](https://github.com/IllinoisGraphBenchmark/IGB-Datasets/blob/1f4628fb7a9f748cd13374ae7de8eebb0a310a07/igb/dataloader.py#L322-L326) to make sure the 'in' edges are on the paper nodes.
