### ISSUE TITLE
Node label fixed to 'node_label_19.npy' in IGBHeteroDGLDataset

### ISSUE THREAD

**Issue by LiSu** [IllinoisGraphBenchmark/IGB-Datasets#22]
**Describe the bug**
It seems that no matter 'num_classes' is set to 19 or 2983,  'node_label_19.npy' is always used in IGBHeteroDGLDataset.
https://github.com/IllinoisGraphBenchmark/IGB-Datasets/blob/main/igb/dataloader.py#L194

**Comment by akhatua2** [comment]
Will fix dataloader. Thanks!

**Comment by msharmavikram** [comment]
@akhatua2 This bug will likely cause accuracy degradation with an increase in the classes. Can we regenerate numbers for this and fix the arxiv paper?
