### ISSUE TITLE
Adding Multi-GPU training script for IGB-Heterogeneous datasets

### ISSUE THREAD

**Issue by Elnifio** [IllinoisGraphBenchmark/IGB-Datasets#27]
**Is your feature request related to a problem? Please describe.**

**Problem**: there are only one-GPU training script available for IGB-Heterogeneous dataset, so it'll be better if we can have a multi-GPU training script, similar to `train_multi_gpu.py`. 

**Solution**: a training script that utilizes all GPUs on a single node to train models on heterogeneous graphs. Initially we can aim for a working version on tiny, small, and medium datasets.

**Comment by msharmavikram** [comment]
The PR is merged to fix this. The read me updated. Thanks for the contributions!
