### ISSUE TITLE
Cannot download datataset programmatically due to dependence on global `args`

### ISSUE THREAD

**Issue by nv-dlasalle** [IllinoisGraphBenchmark/IGB-Datasets#31]
**Describe the bug**
Here https://github.com/IllinoisGraphBenchmark/IGB-Datasets/blob/main/igb/download.py#L85 `args` is referenced, but it is not a parameter to the function. The `args.dataset_size` should just be `dataset_size`.

**Comment by akhatua2** [comment]
Thanks for briging this to our notice @nv-dlasalle. Adderess in #32
