### ISSUE TITLE
Unable to obtain full IGBH-260m

### ISSUE THREAD

**Issue by shizuocheng** [IllinoisGraphBenchmark/IGB-Datasets#35]
Hello author, I have encountered some problems, could you help me solve them?
When I finished downloading IGBH-260m, there were only 3,727,095,830 edges loaded in edge_index.npy. The article shows that IGBH-260m has 3,995,777,033 edges. Even including the self-loop edges, it cannot reach the value of 3,995,777,033. I want to know why these missing edges exist. 
Looking forward to your reply very much
<img width="1047" alt="image" src="https://github.com/IllinoisGraphBenchmark/IGB-Datasets/assets/54357688/6809d307-43cf-48ff-9b74-092b79b96042">

**Comment by shizuocheng** [comment]
And paper_id_index_mapping.npy seems meaningless? After loading edge_index.npy, I found that edge was not in paper_id_index_mapping.

**Comment by akhatua2** [comment]
Hey, thanks for trying out the dataset. I'll check out the mis-match of those ~250M edges and let you know. 

The `paper_id_index_mapping.npy` file simply maps the `mag_paper_id` to our self defined index since the ids can be pretty large numbers.

So essentially the node_feat is an array of node features of papers. And the edge_index.npy file gives you the relation between those array indices. For the most part if you are using the dataloader.py file provided you don't need to worry about the files. 

Please let me know if that made sense :)

**Comment by shizuocheng** [comment]
Thank you for your reply! I used download_igb260m.sh to download IGBH-260m. What if I don’t need to explore the relationship between igb and mag, which means I don’t need to consider paper_id_mapping? Thank you also for your help to look at the missing edge problem.

**Comment by akhatua2** [comment]
Awesome callout. We'll consider adding a flag while downloading to unselect the file. Meanwhile you can always comment out that file in the .sh file @shizuocheng

**Comment by shizuocheng** [comment]
Okay, okay, could you please take a look at the problem of IGB260m edge loss?

**Comment by JIESUN233** [comment]
I have the same issues~

**Comment by akhatua2** [comment]
There is a small discrepency between the number in the diagram and the actual number of edges but if you run the `dataloader.py` file it reads all the `3727095830` paper_cites_paper edges and then adds self loops to get `3996442004` total paper edges.


```bash
>>> ubuntu@ip-172-31-0-186:/mnt/workspace/IGB-Datasets/igb$ python3 dataloader.py 
Graph(num_nodes=269346174, num_edges=3996442004,
      ndata_schemes={'feat': Scheme(shape=(1024,), dtype=torch.float32), 'label': Scheme(shape=(), dtype=torch.int64), 'train_mask': Scheme(shape=(), dtype=torch.bool), 'val_mask': Scheme(shape=(), dtype=torch.bool), 'test_mask': Scheme(shape=(), dtype=torch.bool)}
      edata_schemes={})
```
