### ISSUE TITLE
Download of large dataset is quite slow

### ISSUE THREAD

**Issue by zhuangbility111** [IllinoisGraphBenchmark/IGB-Datasets#54]
Hi! I'm trying to download the `IGB-large` dataset. but I found that it's very slow to download the raw feature file (say .npy file). Do you have any plan about providing the URL for tar.gz or other compression format files instead of the npy files?

**Comment by msharmavikram** [comment]
We did not think of this. Creating a tar.gz is a good idea overall and also giving a md5sum checksum to determine if the download was reliable is a good extension. We will discuss this internally and update this thread.
