### ISSUE TITLE
[Dataset] IGB-HOM dataset wrong number of edges

### ISSUE THREAD

**Issue by BowenYao18** [IllinoisGraphBenchmark/IGB-Datasets#55]
**Describe the bug**
The num edges in paper is 3995777033 in paper but the actual number of edges I download is 3727095830.

**To Reproduce**

Below is the download command:
wget https://igb-public-awsopen.s3.amazonaws.com/IGBH/processed/paper__cites__paper/edge_index.npy
Then, "array = np.load("/path/to/dataset", mmap_mode='r+')" to load the downloaded file and check "arr.shape"

**Expected behavior**
The shape should be (3727095830, 2), which does not match 3995777033 reported in paper.
This is the link to the paper: https://arxiv.org/pdf/2302.13522

**Screenshots**
This is the IGB-HOM info table:
![image](https://github.com/user-attachments/assets/493a8086-4c11-469b-993d-8dae54a9f6c6)

**Software information:**
 - OS, ... 

**Additional context**

**Comment by akhatua2** [comment]
I will update the edge file on the s3 bucket with the local copy soon. It should have the right number of edges. Thanks for bringing this to our attention.

**Comment by BowenYao18** [comment]
> I will update the edge file on the s3 bucket with the local copy soon. It should have the right number of edges (3995777033). Thanks for bringing this to our attention.

Thank you. After the dataset being updated, I should be able to download through the original link?
wget  https://igb-public-awsopen.s3.amazonaws.com/IGBH/processed/paper__cites__paper/edge_index.npy

**Comment by akhatua2** [comment]
Hi, if its urgent please use this [file](https://drive.google.com/file/d/13siqv9b-5KhbY6sJ2eW-6G--BNMqEfTG/view?usp=sharing) as a temporary solution. This is the last 268,681,203 edges. I will upload the `edge_index.npy` file as soon as I can to the s2.

**Comment by BowenYao18** [comment]
Is the edges you are updating a simple remove self edge followed by adding self edge of each node?
edges = add_self_edges(remove_self_edge(edges))

**Comment by akhatua2** [comment]
No these should be edges between different nodes. You can run this `edges = add_self_edges(remove_self_edge(edges))` as a preprocessing step for your usecase.

**Comment by BowenYao18** [comment]
Thank you. Also, I assume het dataset has same paper__cites__paper edges as hom? can I directly use it for the igb-het?

**Comment by akhatua2** [comment]
Both the datasets have the same paper nodes and paper_edges. The het dataset just has more types of nodes and types of edges. 

You can reuse the same edges for both datasets.

**Comment by BowenYao18** [comment]
![image](https://github.com/user-attachments/assets/f5e7851e-5140-4be6-a4a7-80cc7930e8d7)
However, the repo writes that there are 3995777033 edges for the igb-hom and 3996442004 edges for igb-het. Should they be different sets of edges?

**Comment by BowenYao18** [comment]
Also, I don't know if this is a coincidence. but if you try to run `edges = add_self_edges(remove_self_edge(edges))` on the paper__cites__paper edge of the igb-hom, the result will have 3996442004 (the number of edges that the igb-het written in the above graph).

**Comment by akhatua2** [comment]
I believe the number `3996442004` should be the total edges we finally published (including the self edges). There are some inconsistencies between parts of the repo and the paper due to the difference in different internal versions of the full dataset. 

- The het and hom datasets should have the same number of paper edges. We used the edges + self loops count for our initial benchmark runs.

Thanks for pointing it out so I could take a second look. You shouldn't need to use the extra edges as that shouldn't be part of the final dataset. Please use the `edges = add_self_edges(remove_self_edge(edges))` and this will the expected edges for the full dataset (homogeneous and heterogeneous).
