### ISSUE TITLE
[Dataset] IGB-HOM label number

### ISSUE THREAD

**Issue by BowenYao18** [IllinoisGraphBenchmark/IGB-Datasets#56]
In the IGB-HOM dataset, there are only 227130858 (~2.27B) nodes being labeled for the 19-class task and only 153383374 (~1.53B) nodes being labeled in the 2983-class task? (Total nodes is ~ 2.7 B) Is this the expected number?

**Comment by akhatua2** [comment]
Hey,

Yes that's expected as the sources for the 19-class label is from MAG and the semantic scholar while for the 2983 label, its only from the MAG database. So the 2983 class task has less labeled datapoints (~56%) compared to the (~84%) for the 19 class.
