### ISSUE TITLE
[Dataset] Mismatch Number of 2K-class labels for IGB Dataset

### ISSUE THREAD

**Issue by BowenYao18** [IllinoisGraphBenchmark/IGB-Datasets#57]
In the repo, it mentions that the number of 2K_labels is 157675969
https://github.com/IllinoisGraphBenchmark/IGB-Datasets/blob/main/igb/dataloader.py#L63

However, when I download and load the dataset, everything starts to zero out starting after 153383374. Is this a error in the repo?

>>> array = np.memmap("datasets/igb-het/processed/paper/node_label_2K.npy", dtype='float32', mode='r',  shape=(**157675969**))
>>> array[-10:]
memmap([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

>>> array = np.memmap("datasets/igb-het/processed/paper/node_label_2K.npy", dtype='float32', mode='r',  shape=(**153383374**))
>>> array[-10:]
memmap([14., 10., 22., 10., 15.,  1.,  3.,  8.,  4., 23.], dtype=float32)

>>> array = np.memmap("datasets/igb-het/processed/paper/node_label_2K.npy", dtype='float32', mode='r',  shape=(**153383380**))
>>> array[-10:]
memmap([ 3.,  8.,  4., 23.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

**Comment by akhatua2** [comment]
Hello,

Thanks for pointing this out. Yes, it should be `153383374`, probably an incorrect padding on my part.
