### ISSUE TITLE
Missing Genomic Ranges from a BigWig File

### ISSUE THREAD

**Issue by dvl-romero** [IllinoisGraphBenchmark/IGB-Datasets#58]
Hi,

I have a Granges object of 270 ranges that I've converted into a BigWig file (using export.bw( ) function in R from the GenomicRanges Package) then loaded onto IGB (ver 8.3.2). On Chr21, I have 2 differentially methylated regions (DMR), when viewing the entire chromosome. Notice the far right DMR near the 34,129,343 position.
![image (2)](https://github.com/user-attachments/assets/c1a94a92-26c6-41c4-aa25-3a01b9007a20)

However, when I zoom into that region -even just a little- , the DMR completely disappears. I've tried zooming directly at the specific genomic region (start and end position), but even then, the region does not show up.
![image (2) copy](https://github.com/user-attachments/assets/f1bd984d-ef54-430a-b910-1556ee774858)

I know I haven't changed the Y-axis scale of that track or visibility options (I'm using filled bar), and I'm sure the genomes of my Bigwig file and reference match (Hg38 Human). The problem persists regardless of the number of tracks I load into the browser, and it also occurs in the IGV web browser.

Another issues is that some of my DMR regions do not appear entirely. For example, a region with a score of -6.1 does not appear, while a region with a score of -7 does. This indicates it isnt an error within the range or threshold.

Is there something I'm missing? Any advice is appreciated!

**Comment by akhatua2** [comment]
I think you are looking for this (https://www.igb.illinois.edu/). This is the repo for Illinois Graph Benchmark.
